### ISSUE TITLE
existing strapi project

### ISSUE THREAD

**Issue by jafersiddik-ogi** [dimatkach11/strapi_plugins#1]
Its possible to add existing strapi project.
How do connect this existing one.

**Comment by dimatkach11** [comment]
Hi, this is a repository created with dummy data specifically to see how the plugin works which introduces two custom fields. If you want to use the custom fields within another existing project you must copy the entire "**custom-fields**" folder located in **src/plugins/** and place it inside the plugins folder of your project. After that you need to add the following to the **config/plugins.js** file:

```
module.exports = () => ({
   "custom-fields": {
     enabled: true,
     resolve: "./src/plugins/custom-fields",
   },
});
```

However, if you describe your use case I can help you with the configuration of the custom fields, as I haven't yet had time to do decent documentation on how to use them.
