### ISSUE TITLE
how to use in my existing strapi project ?

### ISSUE THREAD

**Issue by iamvermajayant** [dimatkach11/strapi_plugins#3]
Hey, can u help me how to setup this in the existing strapi project ?? @dimatkach11

**Comment by dimatkach11** [comment]
Hi, this is a repository created with dummy data specifically to see how the plugin works which introduces two custom fields. If you want to use the custom fields within another existing project you must copy the entire "**custom-fields**" folder located in **src/plugins/** and place it inside the plugins folder of your project. After that you need to add the following to the **config/plugins.js** file:

```
module.exports = () => ({
   "custom-fields": {
     enabled: true,
     resolve: "./src/plugins/custom-fields",
   },
});
```

However, if you describe your use case I can help you with the configuration of the custom fields, as I haven't yet had time to do decent documentation on how to use them.

**Comment by iamvermajayant** [comment]
Thanks for the making me setting up, Let me tell you my exact use case for eg I have three dropdown fields in content type Manager and in the first dropdown we have 3 values A, B, C  selecting A from first dropdown i want different values to be displayed in my second and third dropdowns and on selecting of B i want some different values to display

**Comment by dimatkach11** [comment]
Hi, I need more details to help you.

If you have the project you are talking about on github and you write me the link, I can make a clone and take a look at the structure of your content types.

Alternatively you can make a Fork of this repo and create your content types inside so that I can have more details.

**Comment by iamvermajayant** [comment]
Hi, Thanks for the help I have already solved the issue, I got the desired results. 
What I was expecting closing the issue now 🫡

Happy Coding 💯
