### ISSUE TITLE
How to select multiple options in subfield ?

### ISSUE THREAD

**Issue by diephoainam089** [dimatkach11/strapi_plugins#5]
In my case, I want to select multiple options in the subfield.
I have the following data tables: Nations, Places, Tours.
- A nation has many places
- A place belongs to a nation
- A tour will belong to a nation and may have many places of that nation.
I tried following your instructions for the Tours data table with the parent field being Nation and the child field being Places (1). When I create an entry, the Place field does not display any options (2). I've looked into it but don't know what's wrong or if the plugin supports multiple selection. Can you help me for this problem?
Thank you very much
(1): Relationship of Tours and Nations, Places
<img width="932" alt="Ảnh màn hình 2024-09-29 lúc 13 33 23" src="https://github.com/user-attachments/assets/f8422d5d-a782-45c6-ad8c-110644c8adcf">
<img width="932" alt="Ảnh màn hình 2024-09-29 lúc 13 22 57" src="https://github.com/user-attachments/assets/ffd01e6c-1757-46fe-839c-5af0bccaafd6">

Custom nation field
<img width="932" alt="Ảnh màn hình 2024-09-29 lúc 13 35 25" src="https://github.com/user-attachments/assets/cdc02373-0100-42b7-84d4-1bcc7c169b94">
<img width="932" alt="Ảnh màn hình 2024-09-29 lúc 13 35 36" src="https://github.com/user-attachments/assets/486615e3-3705-41e3-a702-3eed89e17ab5">

Custom places field
<img width="932" alt="Ảnh màn hình 2024-09-29 lúc 13 35 45" src="https://github.com/user-attachments/assets/880b6254-5d23-4478-91ba-7209b366179e">
<img width="932" alt="Ảnh màn hình 2024-09-29 lúc 13 35 52" src="https://github.com/user-attachments/assets/7a1827c2-d306-4156-ba05-1e70512654c0">

(2):
<img width="1199" alt="Ảnh màn hình 2024-09-29 lúc 13 40 35" src="https://github.com/user-attachments/assets/bf32eabb-3f89-4ae5-b58b-2d537ca642aa">

**Comment by dimatkach11** [comment]
Hi, I created a branch for this issue [5-how-to-select-multiple-options-in-subfield](https://github.com/dimatkach11/strapi_plugins/tree/5-how-to-select-multiple-options-in-subfield), you will find some dammy data that creates two nations and for each nation three associated places. Then see in this branch how I configured the fields. Let me know if I was helpful or if you need anything else

**Comment by diephoainam089** [comment]
Hi, I figured out my problem came from me using a relation field for the place collection because i want to select options instead of text field and I found the solution in issue 2. Your solution worked for me, thank you very much
